#!/usr/bin/env python3
"""
Generate a C++ header file from an icon font.

Reads glyph names and Unicode codepoints from a font file (TTF/OTF/WOFF/WOFF2)
and produces a C++ header with UTF-8 encoded string constants for each icon.

Usage:
    python font_to_header.py <font_file> [options]

Example:
    python font_to_header.py FontAwesome.ttf -o icons.h --prefix FA_ICON_
"""

import argparse
import re
import sys
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError:
    print("Error: fonttools is required. Install with: pip install fonttools", file=sys.stderr)
    sys.exit(1)


def codepoint_to_utf8_literal(cp: int) -> str:
    """Convert a Unicode codepoint to a C++ UTF-8 string literal (hex escaped bytes)."""
    char = chr(cp)
    utf8_bytes = char.encode("utf-8")
    return "".join(f"\\x{b:02X}" for b in utf8_bytes)


def sanitize_name(name: str) -> str:
    """Convert a glyph name into a valid C++ identifier (UPPER_SNAKE_CASE)."""
    # Replace common separators with underscores
    name = re.sub(r"[-./\s]+", "_", name)
    # Remove anything that isn't alphanumeric or underscore
    name = re.sub(r"[^A-Za-z0-9_]", "", name)
    # Collapse multiple underscores
    name = re.sub(r"_+", "_", name)
    # Strip leading/trailing underscores
    name = name.strip("_")
    # Convert to UPPER_SNAKE_CASE
    # Insert underscore before uppercase letters that follow lowercase letters (camelCase)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = name.upper()
    # Ensure it doesn't start with a digit
    if name and name[0].isdigit():
        name = "_" + name
    return name


def extract_glyphs(font_path: str) -> list[tuple[int, str]]:
    """
    Extract (codepoint, glyph_name) pairs from a font file.
    Returns a sorted list of tuples.
    """
    font = TTFont(font_path)

    # Get the best cmap table (Unicode mapping)
    cmap = font.getBestCmap()
    if cmap is None:
        print("Error: No Unicode cmap table found in font.", file=sys.stderr)
        sys.exit(1)

    # cmap is a dict: {codepoint (int): glyph_name (str)}
    glyphs = []
    for codepoint, glyph_name in sorted(cmap.items()):
        # Skip common non-icon entries
        if codepoint < 0x20:  # Control characters
            continue
        glyphs.append((codepoint, glyph_name))

    font.close()
    return glyphs


def generate_header(
    glyphs: list[tuple[int, str]],
    prefix: str,
    guard: str,
    namespace: str | None,
    font_name: str,
    min_codepoint: int | None,
    max_codepoint: int | None,
) -> str:
    """Generate the C++ header file content."""
    lines = []

    lines.append(f"// Auto-generated icon constants from: {font_name}")
    lines.append(f"// Total glyphs: {len(glyphs)}")
    lines.append(f"//")
    lines.append(f"// Generated by font_to_header.py")
    lines.append(f"")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append(f"")

    if namespace:
        lines.append(f"namespace {namespace} {{")
        lines.append(f"")

    # Track names we've already used to avoid duplicates
    used_names: dict[str, int] = {}
    emitted = 0

    for codepoint, glyph_name in glyphs:
        # Apply codepoint range filter
        if min_codepoint is not None and codepoint < min_codepoint:
            continue
        if max_codepoint is not None and codepoint > max_codepoint:
            continue

        # Skip the .notdef glyph and other unnamed entries
        if glyph_name in (".notdef", ".null", "nonmarkingreturn", "CR"):
            continue

        cpp_name = prefix + sanitize_name(glyph_name)

        # Handle duplicate names by appending a suffix
        if cpp_name in used_names:
            used_names[cpp_name] += 1
            cpp_name = f"{cpp_name}_{used_names[cpp_name]}"
        else:
            used_names[cpp_name] = 0

        utf8_literal = codepoint_to_utf8_literal(codepoint)
        lines.append(
            f'constexpr const char {cpp_name}[] = "{utf8_literal}";  // U+{codepoint:04X} ({glyph_name})'
        )
        emitted += 1

    if namespace:
        lines.append(f"")
        lines.append(f"}} // namespace {namespace}")

    lines.append(f"")
    lines.append(f"#endif // {guard}")
    lines.append(f"")

    print(f"Emitted {emitted} icon constants.", file=sys.stderr)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a C++ header with icon font Unicode constants."
    )
    parser.add_argument("font", help="Path to the font file (TTF, OTF, WOFF, WOFF2)")
    parser.add_argument(
        "-o", "--output", help="Output header file path (default: stdout)"
    )
    parser.add_argument(
        "--prefix",
        default="ICON_",
        help="Prefix for constant names (default: ICON_)",
    )
    parser.add_argument(
        "--guard",
        default=None,
        help="Include guard name (default: derived from output filename)",
    )
    parser.add_argument(
        "--namespace",
        default=None,
        help="Wrap constants in a C++ namespace",
    )
    parser.add_argument(
        "--min-codepoint",
        default=None,
        type=lambda x: int(x, 0),
        help="Minimum codepoint to include (e.g. 0xE000 for Private Use Area)",
    )
    parser.add_argument(
        "--max-codepoint",
        default=None,
        type=lambda x: int(x, 0),
        help="Maximum codepoint to include (e.g. 0xF8FF)",
    )
    parser.add_argument(
        "--list-only",
        action="store_true",
        help="Just list glyphs found in the font, don't generate header",
    )

    args = parser.parse_args()

    # Extract glyphs
    glyphs = extract_glyphs(args.font)
    print(f"Found {len(glyphs)} glyphs in {args.font}", file=sys.stderr)

    # List mode
    if args.list_only:
        for cp, name in glyphs:
            print(f"U+{cp:04X}  {name}")
        return

    # Determine include guard
    if args.guard:
        guard = args.guard
    elif args.output:
        guard = Path(args.output).stem.upper().replace("-", "_").replace(".", "_") + "_H"
    else:
        guard = "ICONS_H"

    font_name = Path(args.font).name

    header = generate_header(
        glyphs,
        prefix=args.prefix,
        guard=guard,
        namespace=args.namespace,
        font_name=font_name,
        min_codepoint=args.min_codepoint,
        max_codepoint=args.max_codepoint,
    )

    if args.output:
        Path(args.output).write_text(header)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(header)


if __name__ == "__main__":
    main()
